export const initialData = [
  {
    id: 1,
    applied: 3,
    name: 'Program 1',
    students: [
      {
        score1: '8.33',
        score2: '8.33',
        score3: '8.33',
        score4: '8.33',
        program: 'Casper',
        canEnroll: true,
        name: 'Student 1',
        image: '/images/avatar.png',
        email: 'Isabellading@gmail.com',
        pastTest: [
          {
            id: 1,
            course: 'Human Gross Anatomy',
            pastTest: 'Quiz 1',
            score: '8.33',
          },
          {
            id: 2,
            course: 'Histology',
            pastTest: 'Quiz 4',
            score: '8.33',
          },
          {
            id: 3,
            course: 'Clinical Anatomy',
            pastTest: 'Quiz 2',
            score: '8.33',
          },
        ],
      },
      {
        score1: '8.33',
        score2: '8.33',
        score3: '8.33',
        score4: '8.33',
        name: 'Student 2',
        program: 'Formative',
        canEnroll: false,
        image: '/images/avatar.png',
        email: 'Isabellading@gmail.com',
      },
      {
        score1: '8.33',
        score2: '8.33',
        score3: '8.33',
        score4: '8.33',
        name: 'Student 3',
        program: 'Formative',
        canEnroll: false,
        image: '/images/avatar.png',
        email: 'Isabellading@gmail.com',
      },
      {
        score1: '8.33',
        score2: '8.33',
        score3: '8.33',
        score4: '8.33',
        name: 'Student 4',
        program: 'Formative',
        canEnroll: false,
        image: '/images/avatar.png',
        email: 'Isabellading@gmail.com',
      },
    ],
  },
];
